### PR TITLE
Removed unused code, updated README and added callback functions on SimplePlayes

### PR DESCRIPTION
**Pull request by willy2dg**
Included callbacks for play and pause on SimplePlayer.
Removed some obsolete code.
Updated README.md

### CODE REVIEW

**Comment by inwady** [comment]
Oops, @willy2dg, there is error in the test (`isIdleNow`). Fix it, please.

**Comment by willy2dg** [comment]
@inwady done, i forgot to change the variable name there.

**Comment by inwady** [comment]
In order to prevent similar errors could you add `.circleci` files for compile project and CI?

**Comment by willy2dg** [comment]
@inwady I'm sorry but I don't know how it works, it seems an additional task anyway. I will look at it in my spare time once we close this. But the initial issue is solved.

**Comment by inwady** [comment]
Thanks! Go to the issue.

**Comment by willy2dg** [comment]
@inwady Thanks to you, I checked the issue, but it's still open.

**Comment by willy2dg** [comment]
@ntk can you accept the claim please ?

**Pull request merged**
